swagger: "2.0"
info:
  version: "0.1"
  title: "monorepo API"
  description: "An API to test a monorepo"
basePath: /Prod
schemes:
- https
paths:
  /alambda:
    get:
      description: "gets something"
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: "Profile Created"
          schema:
            $ref: "#/definitions/Response"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/Response"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/Response"
        404:
          description: "Not Found"
          schema:
            $ref: "#/definitions/Response"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/Response"
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ALambda.Arn}/invocations"
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
  /blambda:
    get:
      description: "gets something"
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: "Profile Created"
          schema:
            $ref: "#/definitions/Response"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/Response"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/Response"
        404:
          description: "Not Found"
          schema:
            $ref: "#/definitions/Response"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/Response"
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BLambda.Arn}/invocations"
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
definitions:
  Response:
    type: object
    required:
      - message
    properties:
      message:
        type: "string"
        title: "The Error message" 